language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 7.0
  - 5.6

matrix:
  fast_finish: true

# We only build pushes to master and pull requests
branches:
  only:
    - master

before_install:
  # Disable XDebug speeds up composer
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer install --no-interaction --prefer-dist --ignore-platform-reqs
  # Re-enable XDebug for phpunit code coverage
  - echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mkdir -p build/logs

script:
  - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - travis_retry php coveralls.phar -v
